<a href="https://colab.research.google.com/github/davinnnnn/first-repository/blob/main/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
import torch.nn as nn

device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(2022)
if device == 'cuda':
    torch.cuba.manual_seed_all(2022)

X = torch.FloatTensor([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
]).to(device)

Y = torch.FloatTensor([
    [0],[1],[1],[0]
]).to(device)

model = nn.Sequential(
    nn.Linear(2,1,bias = True),
    nn.Sigmoid()
).to(device)

loss_func = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(),lr = 0.01)

for step in range (20001):
    optimizer.zero_grad()

    Y_hat = model(X)
    loss = loss_func(Y_hat, Y)
    loss.backward()
    optimizer.step()

    if step % 1000 == 0:
        print(step, loss.item())

    with torch.no_grad():
        model.eval()
        inputs = torch.FloatTensor([[0,0],[0,1],[1,0],[1,1]]).to(device)
        outputs = model(inputs)

        print(outputs)
        print(outputs > 0.01)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
        [0.5000],
        [0.5000],
        [0.5000]])
tensor([[True],
        [True],
        [True],
        [True]])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]])
tensor([[True],
        [True],
        [True],
        [True]])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]])
tensor([[True],
        [True],
        [True],
        [True]])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]])
tensor([[True],
        [True],
        [True],
        [True]])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]])
tensor([[True],
        [True],
        [True],
        [True]])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]])
tensor([[True],
        [True],
        [True],
        [True]])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]])
tensor([[True],
        [True],
        [True],
        [True]])
tensor([[0.5000]